version: '3.9'

services:
    app:
        build: .
        ports:
            - '5000:5000'
        environment:
            - DATABASE_LOCAL=mongodb://mongo:27017/task-management
            - PORT=5000
            - JWT_SECRET=verysecretkeygoeshere
            - JWT_EXPIRES_TIME=7d
            - FRONTEND_URL=http://localhost:5173
            - USER_ID=demo2023acount@gmail.com
            - APP_PASS=cppjxafrrjcsjvkb
            - SENDER_EMAIL=demo2023acount@gmail.com
        depends_on:
            - mongo
        command: npm run dev
        volumes:
            - ./images:/app/images
            - ./logs:/app/logs

    mongo:
        image: mongo:7
        command: ['mongod', '--quiet']
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
